### ISSUE TITLE
Переделать на стрелочные функции

### ISSUE THREAD

**Issue by dzencot** [hexlet-basics/exercises-typescript#100]
Переделать `function` на стрелочные функции там, где это возможно

**Comment by mokevnin** [comment]
Специально делал функции

**Comment by dzencot** [comment]
Ааа. А я у Васи спрашивал, он сказал что так получилось. https://code-basics.com/ru/languages/typescript/lessons/destructuring#comment-6073596953 - студент спрашивает почему не стрелочные

**Comment by bondiano** [comment]
@mokevnin, а напомни зачем? я дальше в уроках использую стрелочные функции
