### ISSUE TITLE
Спасибо за предложение, информация полезная, но для решения текущего задания точно не нужна, пока урок, где эта информация могла быть бы уместна не написан

### ISSUE THREAD

**Issue by realing29** [hexlet-basics/exercises-typescript#125]
Спасибо за предложение, информация полезная, но для решения текущего задания точно не нужна, пока урок, где эта информация могла быть бы уместна не написан

_Originally posted by @bondiano in https://github.com/hexlet-basics/exercises-typescript/issues/124#issuecomment-1375100346_
      
Ссылка на урок - https://code-basics.com/ru/languages/typescript/lessons/type-annotations#editor
Как это не нужна... В уроке аннотация типов, в решении учителя используется (as number[]):
// BEGIN
function compact(items: (number | null)[]): number[] {
  return items.filter((item) => item !== null) as number[];
}
// END

Без него тесты не проходят и про него нигде не упоминается.
Что бы ученик мог решить самостоятельно задание он должен о нём знать.

**Comment by realing29** [comment]
Можно хотя бы упомянуть, что для решения нужно использовать `val is`.

**Comment by v1valasvegan** [comment]
Сорри, это я забыл, что приведение типов еще не проходили. Как вариант, можно сначала записать результат в константу и аннотировать тип.
```
function compact(items: (number | null)[]): number[] {
  const result: number[] = items.filter((item) => item !== null);
  return result;
}
```
Или вернуть как было `function compact(...): (number | null)[]`, хотя типизация кривая в итоге получается.

**Comment by v1valasvegan** [comment]
Еще варик – изменить само задание, попросить написать функцию `uniq`, которая убирает повторы из массива. В массиве могут быть строки или числа, тогда можно обойтись без приведения типов и хака с аннотацией результата:
```
const init: (number | string)[] = [];

const uniq = (coll: (number | string)[]): (number | string)[] => (
  coll.reduce((acc, curr) => (
    acc.includes(curr)
    ? acc
    : [...acc, curr]
  ), init)
)
```

**Comment by realing29** [comment]
> Еще варик – изменить само задание, попросить написать функцию `uniq`, которая убирает повторы из массива. 
Хороший вариант. У кого-нибудь найдется время.

**Comment by v1valasvegan** [comment]
Если всех устраивает сделаю сегодня вечером.

**Comment by bondiano** [comment]
ага, давайте заменим задание

**Comment by v1valasvegan** [comment]
> Это решение съест вызов
uniq([1, 1, 3, 'oops!'])

Да, немного криво получается. Однако, [1, 1, 3, 'oops!']  подходит под определение `массив чисел или строк`, хотя изначально, конечно, не это имелось в виду, и функция отрабатывает корректно. В оригинально задании с `compact` были составные типы `(number | null)[]`, и хотелось бы их сохранить.

В общем, предлагаю или так оставить, или переделать на `массив чисел`, если наличие составных типов не принципиально.
