### ISSUE TITLE
Решение в задании требует ещё непройденного материала

### ISSUE THREAD

**Issue by ssssank** [hexlet-basics/exercises-typescript#131]
В уроке https://code-basics.com/ru/languages/typescript/lessons/anonymous-functions в решении используется указание типа массива`number[]`, но массивы объясняются только в следующем уроке

**Comment by reznikovAndrey** [comment]
Переписал с использованием анонимной функции (у нас же урок про них) + просто убрал тип возвращаемого значения из функции.

Получилось по аналогии с примером из теории за тем исключением, что в теории используется `.map`, а в решении учителя - `.filter()`
