### ISSUE TITLE
Используется тема, которая изучается в следующем уроке

### ISSUE THREAD

**Issue by ravelin9** [hexlet-basics/exercises-typescript#135]
[Тема: Анонимные функции](https://code-basics.com/ru/languages/typescript/lessons/anonymous-functions)
В решении задачи используется тип массива, но объясняется про типы массивов только в следующем уроке

### Решение учителя:

```
const numbers = [1, 3, 8, 9, 100, 23, 55, 34];

// BEGIN
function getEvenNumbers(): number[] {
  const evenNumbers = numbers.filter((n) => n % 2 === 0);

  return evenNumbers;
}
// END

export default getEvenNumbers;
```

**Comment by reznikovAndrey** [comment]
Дублирование, нет?

https://github.com/hexlet-basics/exercises-typescript/issues/131

**Comment by bondiano** [comment]
да, дубль

**Comment by ravelin9** [comment]
пардоньте
