### ISSUE TITLE
Ошибка в решении учителя "Объектные типы (Object Types)" 7/55

### ISSUE THREAD

**Issue by evgeniyworkbel** [hexlet-basics/exercises-typescript#153]
Определение параметров записано неверно: 
`function isComplete(course: { name: string, lessons: string[] }): boolean {`

Обьектный тип указан через запятую, а нужно через двоеточие.  Вот из урока:

"Чтобы принять такой объект в функцию как параметр, нужно указать его структуру в описании функции:
`
// Свойства в описании типа разделяются через точку с запятой (;)
function doSomething(user: { firstName: string; pointsCount: number; }) {
  // ...
`
}"

Также в этом же примере из урока в параметре pointsCount после него не требуется точка с запятой - это насколько я понимаю инлайновая запись обьекта. В офф. доке не ставят https://www.typescriptlang.org/docs/handbook/2/objects.html

**Comment by bondiano** [comment]
в дальнейших уроках также используется запись через `,`, разницы между записями нет, просто стилистическая особенность.

В уроке заменил описание на `,`
