### ISSUE TITLE
Добавить ответы на задачи

### ISSUE THREAD

**Issue by evgeniyworkbel** [hexlet-basics/exercises-typescript#154]
Не хватает кнопки "Подсказка" как сделано на Хекслете: когда сталкиваешься с проблемой решения задачи, то ответ учителя никак не посмотришь и потом себя не зарефакторишь. В слаке можно долго жддать и не дождаться помощи

**Comment by bondiano** [comment]
<img width="1172" alt="Снимок экрана 2023-02-25 в 13 41 31" src="https://user-images.githubusercontent.com/323479/221345305-061a4d5c-c050-4ff3-a717-7a05276dbbcd.png">

На code-basics есть такая функциональность. Или вы о другом?

**Comment by evgeniyworkbel** [comment]
@bondiano да, я уже заметил. 

Может кому-то понадобится:
решение можно посмотреть спустя 20 минут и только в случае, если ты еще ни разу не нажимал кнопу "Проверить"
