### ISSUE TITLE
Тип Void :: Описание метода push()

### ISSUE THREAD

**Issue by oltov** [hexlet-basics/exercises-typescript#180]
https://github.com/hexlet-basics/exercises-typescript/blob/0f4a22168c26ef02bd76ac925db63104c46abd91/modules/20-functions/30-void/description.ru.yml#L25

Написано что метод `push()` возвращает индекс добавленного элемента, но в JS он возвращает новую длину массива.

**Comment by semenChe** [comment]
Я сделаю это исправление.

**Comment by bondiano** [comment]
Спасибо!
