### ISSUE TITLE
Пересмотр уроков курса с учетом поправки

### ISSUE THREAD

**Issue by evgeniyworkbel** [hexlet-basics/exercises-typescript#236]
В [уроке про алиасы типов](https://code-basics.com/ru/languages/typescript/lessons/type-aliases) есть такой абзац:

_При этом разработчики на TypeScript говорят «создал тип», а не «создал псевдоним типа». Поэтому в этом курсе мы будем придерживаться общепринятого формата._

Не понимаю, зачем учить неправильно. Создать тип - это создать тип, создать алиас типа - это создать алиас типа и никак иначе. Подход, что "правильно вот так, но мы будем придерживаться общепринятого называния" порождает следствия, когда разработчики будут говорить по-разному и потом путаться, хотя речь шла об одной и той же вещи.

Мне кажется стоит скорректировать курс, чтобы в этом уроке и далее было правильно, а именно: если создаем алиас типа, то и пишем в уроке или задании, что "нужно создать алиас типа", а не "нужно создать тип"

**Comment by bondiano** [comment]
В официальной документации также используется "создали тип", а не "создали псевдоним типа". 

В абсолютном большинстве статей также пишут "создадим тип". И это не вызывает сложностей и проблем в общении.
