### ISSUE TITLE
Откорректировать наименования алиасов типов в решении учителя

### ISSUE THREAD

**Issue by evgeniyworkbel** [hexlet-basics/exercises-typescript#237]
Вместо OpitonName, OpitonSize исправить на OptionName, OptionSize

![image](https://github.com/hexlet-basics/exercises-typescript/assets/93836126/4f9108fc-f439-4a88-84b4-a95f2350ffaf)

**Comment by bondiano** [comment]
Вы можете прислать свой PR с правками

**Comment by evgeniyworkbel** [comment]
> Вы можете прислать свой PR с правками

взял в работу

**Comment by evgeniyworkbel** [comment]
@bondiano Василий, подскажите как запустить проект у себя на локалхосте?

**Comment by bondiano** [comment]
@evgeniyworkbel в блоге Хекслета есть прекрасный гайд https://ru.hexlet.io/blog/posts/participate-in-open-source#forking

**Comment by evgeniyworkbel** [comment]
> @evgeniyworkbel в блоге Хекслета есть прекрасный гайд https://ru.hexlet.io/blog/posts/participate-in-open-source#forking

да, я читал его. Он не помог с ответом на вопрос

**Comment by bondiano** [comment]
Вам нужно сделать форк, склонировать его, сделать правки, запушить в отдельную ветку форка, открыть ПР в это репо

**Comment by evgeniyworkbel** [comment]
> Вам нужно сделать форк, склонировать его, сделать правки, запушить в отдельную ветку форка, открыть ПР в это репо

как контрибьютить я знаю, но я ведь о другом: не получается склонировать ни репо, ни форк этого репо в /opt/projects, как того требует ридми hexlet-basics

**Comment by evgeniyworkbel** [comment]
> > Вам нужно сделать форк, склонировать его, сделать правки, запушить в отдельную ветку форка, открыть ПР в это репо
> 
> как контрибьютить я знаю, но я ведь о другом: не получается склонировать ни репо, ни форк этого репо в /opt/projects, как того требует ридми hexlet-basics

решил

**Comment by evgeniyworkbel** [comment]
@bondiano Василий, привет! Можешь подсказать по этому [вопросу](https://t.me/hexletcommunity/12/60931)?
