### ISSUE TITLE
No such file or directory: 'modules/10-basics/20-typescript-as-a-second-language/./description.en.yml'

### ISSUE THREAD

**Issue by evgeniyworkbel** [hexlet-basics/exercises-typescript#238]
При первой установке проекта в процессе запуска make compose и make compose-schema-validate возникают ошибки доступа к файлам, которые отвечают за англ дескрипшн

![Screenshot from 2023-08-25 22-50-34](https://github.com/hexlet-basics/exercises-typescript/assets/93836126/47974fa1-db63-4011-86a2-902b330c5853)

![Screenshot from 2023-08-26 00-43-20](https://github.com/hexlet-basics/exercises-typescript/assets/93836126/b85fcf1b-8889-4c44-a219-1ce7efcb7fa2)

**Comment by usernaimandrey** [comment]
это нормальное поведение, так везде где еще нет англю версии, главное что бы команда  make ci-check завершалась с кодом 0 - что бы проходили все тесты и валидация description.ru.yml

**Comment by evgeniyworkbel** [comment]
> это нормальное поведение, так везде где еще нет англю версии, главное что бы команда make ci-check завершалась с кодом 0 - что бы проходили все тесты и валидация description.ru.yml

да, завершается с 0. Спасибо за помощь, ишьюс закрываю
