### ISSUE TITLE
Добавить урок про предикаты в TS

### ISSUE THREAD

**Issue by evgeniyworkbel** [hexlet-basics/exercises-typescript#245]
https://www.typescriptlang.org/docs/handbook/2/narrowing.html#using-type-predicates

В документации не очень понятно, как правильно применять предикаты в TS. Было бы неплохо добавить такой объясняющий урок

**Comment by fey** [comment]
По сути про это есть урок, https://code-basics.com/ru/languages/typescript/lessons/type-narrowing
