### ISSUE TITLE
error    syntax error: expected <block end>, but found '<block mapping start>' (syntax)

### ISSUE THREAD

**Issue by evgeniyworkbel** [hexlet-basics/exercises-typescript#249]
При выполнении make compose ошибка

![image](https://github.com/hexlet-basics/exercises-typescript/assets/93836126/6dd1e41d-a3f4-44e3-946d-f6bb8c0ec1ef)

**Comment by evgeniyworkbel** [comment]
сделать отступы в yaml файле меньше.

Взял в работу

**Comment by evgeniyworkbel** [comment]
ошибка была исправлена @fey коммитом ba853e

**Comment by fey** [comment]
Это был @dzencot :D
