### ISSUE TITLE
Урок 11, Система модулей. Добавить комментарий о том, что namespace-ы расходятся с нынешней концепций TS

### ISSUE THREAD

**Issue by gurianov-p** [hexlet-basics/exercises-typescript#267]
В этом интервью говорится, что namespace-ы бы не добавляли в язык, если бы на тот момент была система EcmaScript модулей
https://www.youtube.com/watch?v=tXK50czRbdA&t=990s

Так же, насколько понимаю, namepspace-ы, как и enum-ы, расширяют синтаксис языка вместо просто добавления статической проверки типов.

**Comment by bondiano** [comment]
Все так, я в уроке тоже об этом писал. Или в чем ваше предложение?

> В этом уроке рассмотрим систему модулей TypeScript, которая была создана до стандартизации ESM-модулей.

**Comment by gurianov-p** [comment]
А, точно. Пропустил этот момент
