### ISSUE TITLE
Урок Тип Void - опциональный параметр

### ISSUE THREAD

**Issue by fey** [hexlet-basics/exercises-typescript#64]
Ранее в уроке про опциональные параметры [говорилось](https://github.com/hexlet-basics/exercises-typescript/blob/main/modules/20-functions/20-optional-parameters-in-callbacks/description.ru.yml), что в колбеках лучше передавать все параметры без опциональности. При этом в [решении учителя](https://github.com/hexlet-basics/exercises-typescript/blob/main/modules/20-functions/30-void/index.ts#L2) в уроке void это игнорируется и второй параметр в коллбеке опционален.

**Comment by bondiano** [comment]
действительно, это один из кейсов, где вообще лучше использовать перегрузку с разным числом параметров, подумаем над заданием
