### ISSUE TITLE
Урок Многомерные массивы - тесты не проверяют наличие строк в поле

### ISSUE THREAD

**Issue by fey** [hexlet-basics/exercises-typescript#87]
По условию задания мы должны создать поле, которое принимает тип `string | null`. Но тесты проверяют только null.

Можно модифицировать условие и передавать в функцию не только размер но и начальное значение ячейки.

**Comment by txmrv** [comment]
Передавать начальное значение в функцию было бы странно, т.к. инициализированное поле для игры должно быть пустым.
Проще в тестах создать перменную поля и попробовать присвоить значение в ячейку, что имитировало бы ход игрока.


Не совсем уверен в своем коде, но выглядело бы примерно так:
```ts
const field = getField(1);
expect(field).toEqual([[null]]);
filed[0][0] = 'x';
expect(field).toEqual([['x']]);
```

Вообще, тип ячейки мог бы вяглядеть, как `type Cell = 'x' | 'o' | null;`

**Comment by txmrv** [comment]
Если решение устроит, позвольте мне попрактиковать пулреквест по номеру ишью)

**Comment by fey** [comment]
@bondiano

**Comment by bondiano** [comment]
@txmrv тут про инициализацию поля, поправим описание, спасибо!

**Comment by txmrv** [comment]
@bondiano теперь как- то странно получается, что ячейки игрового поля могут содержать только `null`
