### ISSUE TITLE
Add return type

### ISSUE THREAD

**Issue by VadimFilimonov** [hexlet-basics/exercises-typescript#92]
В уроке Именованные функции [есть](https://github.com/hexlet-basics/exercises-typescript/blob/main/modules/10-basics/40-named-functions/description.ru.yml#L68) такое утверждение:

> Несмотря на то, что возвращаемый тип может выводиться, мы рекомендуем проставлять его всегда...

Если посмотреть примеры кода и решения учителя в последующих уроках, то там возвращаемый тип указан не будет.
Это сбивает с толку.

**Comment by bondiano** [comment]
Да, все верно, в уроках встречаются примеры, где нет части тела функции, так что добавил везде, где в этом есть смысл
